sudo: false
language: node_js
node_js:
  - "8"
  - "10"

before_install:
  - travis_retry npm install

script:
  - npm run test-with-coverage

notifications:
  email:
    - michel+opensource@michelbitter.nl